name: OANDA Trading Bot

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installs specific, stable versions of all required libraries
          pip install "numpy==1.23.5" setuptools "pandas==1.5.3" "pandas-ta==0.3.14b" oandapyV20 requests

      - name: Run Trading Bot
        env:
          OANDA_ACCESS_TOKEN: ${{ secrets.OANDA_ACCESS_TOKEN }}
          OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        run: python oanda_bot.py
