name: OANDA Trading Bot

on:
  schedule:
    # Runs every 15 minutes. Use '*/5 * * * *' for every 5 minutes, 
    # but be mindful of your free minutes usage.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pandas_ta oandapyV20

      - name: Run Trading Bot
        env:
          OANDA_ACCESS_TOKEN: ${{ secrets.OANDA_ACCESS_TOKEN }}
          OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        run: python oanda_bot.py
