name: OANDA Trading Bot

on:
  schedule:
    # Runs every 15 minutes.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # THE FIX IS HERE: Added 'requests' to the install list
          pip install "numpy==1.23.5" setuptools pandas pandas_ta oandapyV20 requests

      - name: Run Trading Bot
        env:
          OANDA_ACCESS_TOKEN: ${{ secrets.OANDA_ACCESS_TOKEN }}
          OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        run: python oanda_bot.py
